name: Docker Image CI

on: [push]

jobs:

  build-release:
    name: Build & Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: ./docker-build.sh "${GITHUB_REF_SLUG}"
    - name: Release Docker image
      if: ${{ github.ref != 'refs/heads/main' }}
      run: docker push "mrsarm/dcoleman-e2e:${GITHUB_REF_SLUG}"
    - name: Tag "latest"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker tag "mrsarm/dcoleman-e2e:${GITHUB_REF_SLUG}" mrsarm/dcoleman-e2e:latest
    - name: Release "latest"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push mrsarm/dcoleman-e2e:latest
