name: Playwright Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: ./docker-build.sh
      # TODO run tests
#    - name: Install Playwright Browsers
#      run: npx playwright install --with-deps
#    - name: Run Playwright tests
#      run: npx playwright test
#    - uses: actions/upload-artifact@v4
#      if: always()
#      with:
#        name: playwright-report
#        path: playwright-report/
#        retention-days: 30
